openapi: 3.0.0
info:
  $ref: ./info/index.yaml
servers:
  - $ref: ./servers/index.yaml
security:
  - defaultSecuritySchema: [read:parties write:parties]
components:
  schemas:
    $ref: ./components/schemas/index.yaml
  parameters:
    $ref: ./components/parameters/index.yaml
  examples:
    $ref: ./components/examples/index.yaml
  requestBodies:
    $ref: ./components/requestBodies/index.yaml
  responses:
    $ref: ./components/responses/index.yaml
  headers:
    $ref: ./components/headers/index.yaml
  securitySchemes:
    $ref: ./components/securitySchemes/index.yaml
paths:
    $ref: ./paths/index.yaml
